src = ["flows"]

# Use Ruff for sorting imports
lint.extend-select = ["I"]

# Do not enforce line length; black does this for code and we do not care about comments / docs
lint.ignore = ["E501"]

[lint.isort]
known-third-party = ["prefect._vendor"]