name: Build image and deploy Prefect flow - Project 1

env:
  PROJECT_NAME: flows/aws

on:
  push:
    paths:
      - "flows/aws/**"
  workflow_dispatch:

jobs:
  deploy:
      name: Deploy AWS flows
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"
            cache: "pip"

        - name: Filter Paths
          uses: dorny/paths-filter@v3
          id: filter
          with:
            # Changed file can be 'added', 'modified', or 'deleted'.
            # By default, the type of change is not considered.
            # Optionally, it's possible to specify it using nested
            # dictionary, where the type of change composes the key.
            # Multiple change types can be specified using `|` as the delimiter.
            filters: |
              addedOrModified:
                - added|modified: 'flows/aws/**'
            
