name: "Build and Apply a Prefect deployment for a flow in development workspace"
on:
  push: # or on changes to paths in branches
    branches:
      - "development"
    paths:
       - "flows/hello_world_flow/hello_world_flow.py"

# change as needed
env:
  DEPLOYMENT_NAME: hello_world_automated_deployment
  FLOW_FILE: flows/hello_world_flow/hello_world_flow.py
  ENTRYPOINT: hello_world
  FILESYSTEM_EXTRAS: s3fs
  STORAGE: s3/flow-code-storage2
  WORK_QUEUE: local-laptop
  #We add API keys in as a secret in the Github UI
  PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }} 
  PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

jobs:
  prefect-deployment-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Update Pip and required filesystem extras
        run: pip install -U wheel pip $FILESYSTEM_EXTRAS

      - name: Add Flow Dependencies (including Prefect)
        run: pip install -r requirements.txt

      - name: Login to Prefect 
        run: prefect cloud login --key $PREFECT_API_KEY --workspace sales-engineering/development
      
      - name: Cd to Flow Directory 
        run: cd ./flows/hello_world_flow

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_BUCKET_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_BUCKET_USER_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Authenticate to AWS 
        run: aws s3 ls

      - name: Build / Apply deployment
        run: |
          prefect deployment build ./$FLOW_FILE:$ENTRYPOINT --name $DEPLOYMENT_NAME --work-queue $WORK_QUEUE --storage-block $STORAGE --output ./my_manifest.yml --apply

     
      - name: Output Success
        run: echo "Successfully built and applied ${{ env.DEPLOYMENT_NAME }} :rocket:" >> $GITHUB_STEP_SUMMARY